spring.application.name=md3_project

spring.datasource.url=jdbc:postgresql://localhost:5432/md3_project
spring.datasource.username=postgres
spring.datasource.password=kimquan1
spring.datasource.driver-class-name=org.postgresql.Driver

# C?u hình JPA/Hibernate
spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret-key=9gf8394hf34f3489fh3849hf9348dsbhdsbhsdbvndjfcndsjfdjfjdsfj
jwt.expired=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=daoanhquan2k3@gmail.com
spring.mail.password=suduqudiilmzgdic
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
